[package]
name = "ripnode"
version = "0.1.0"
description = "Simple tool for deleting node_modules and other folders"
license = "MIT"
authors = ["Jorge Mayoral Álvarez <mayoralalvarezj@gmail.com>"]
repository = "https://github.com/JorgeMayoral/ripnode"
edition = "2021"

[lib]
path = "src/lib.rs"

[[bin]]
path = "src/main.rs"
name = "ripnode"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytesize = "1.2.0"
clap = { version = "4.1.8", features = ["derive"] }
fs_extra = "1.3.0"
