[package]
name = "ripnode"
version = "0.1.0"
authors = ["Jorge Mayoral Álvarez <mayoralalvarezj@gmail.com>"]
edition = "2021"

[lib]
path = "src/lib.rs"

[[bin]]
path = "src/main.rs"
name = "ripnode"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytesize = "1.1.0"
fs_extra = "1.3.0"
